### ISSUE TITLE
Allow users to override default service images in .pygmy.yml

### ISSUE THREAD

**Issue by tobybellwood** [fubarhouse/pygmy#458]
To allow local customisation, and facilitate easier testing, you should be able to define the image for a built-in service in the .pygmy.yml file (as you can for external services).

This would allow easier testing in the image repos etc

e.g.
```
services:
  amazeeio-haproxy:
    image: ghcr.io/pygmystack/haproxy:pr-12
  amazeeio-ssh-agent:
    image: ghcr.io/pygmystack/ssh-agent:pr-2
  amazeeio-dnsmasq:
    image: ghcr.io/pygmystack/dnsmasq:pr-2
  amazeeio-mailhog:
    image: ghcr.io/pygmystack/mailhog:pr-3
 ```
